### ISSUE TITLE
fiil mask holes option breaks feathered mask

### ISSUE THREAD

**Issue by RoyDingZF** [lquesada/ComfyUI-Inpaint-CropAndStitch#13]
if this option is enabled, the feathered mask becomes hard edge mask.

**Comment by lquesada** [comment]
Hi! I'll check this soon, but there's a chance that it cannot be fixed properly within the node.

In the meanwhile, the obvious workarounds are
1) fill holes manually, haha
2) apply feather after the crop node

**Comment by RoyDingZF** [comment]
Haha, I would avoid using auto fill hole for now.

**Comment by lquesada** [comment]
hey :) there's no proper way to fix this, but... I have just integrated a "blur mask" and a "blend" option in the node, so you shouldn't need an external feather mask node anymore. Check the new workflow example in github.

(this was a breaking change because I added new parameters to the node, so you/everyone will have to recreate the node - sorry!)

I'll mark this as closed.
