### ISSUE TITLE
A request about video support.

### ISSUE THREAD

**Issue by magang84** [lquesada/ComfyUI-Inpaint-CropAndStitch#17]
Hello, could there be an additional option to support that when cropping an image according to a mask, the area within the mask is not enlarged or reduced, and instead the surrounding content is filled (can be filled externally if exceeded) to achieve a unified size. In this way, it can ensure the continuity of the consecutive image content taken (such as character movements) and better support Video AnimateDiff Evolved (I am using it for the redrawing of partial video content). The current situation is that the optimal enlargement of the mask content is ensured for redrawing, but this cannot support the redrawing of continuous images (with very large jitter), because the size of the mask content is not consistent as the camera moves. Thank you very much for your great dedication.

**Comment by lquesada** [comment]
hi!

not really :)) The node worked like that originally, and the results were extremely inconsistent and terrible. The models are so much more consistent at generating something when it's a similar size. Switching to rescale over time turned out to work great.

There's a workaround that ensures a consistent amount of context plus a consistent size on the area to generate. Set context_expand_factor to a higher value, like 2, 3, or 4. This will always add ~the same amount of context and keep the mask ~the same relative size, so way better consistency.

I'd also encourage you to use forced size mode if you're doing this.

Ranged size would yield slightly higher quality as it allows for more aspect ratios to adjust better to the masked area, but may be a bit more inconsistent.

**Comment by magang84** [comment]
Thank you very much for your answer.
