### ISSUE TITLE
ComfyUI crashes on Inpaint Crop node

### ISSUE THREAD

**Issue by Shyryp** [lquesada/ComfyUI-Inpaint-CropAndStitch#32]
The problem appears when I start using "Inpaint Crop" in the new ComfyUI functionality - loops from [@guill](https://github.com/guill).

After about 20-30 loops inside ForLoop, the program crashes on your "Inpaint Crop" node, without any error. I have no idea yet why exactly this could happen, I can't catch the error.

Here is an example of a workflow. You can run it yourself and check if ComfyUI will crash.
[LoopTest.json](https://github.com/user-attachments/files/16738387/LoopTest.json)

I used your nodes on the latest version of ComfyUI.

For loops, I used this package (from the same author ([@guill](https://github.com/guill)) who implemented Execution Model Inversion in ComfyUI a week ago): https://github.com/BadCafeCode/execution-inversion-demo-comfyui

[@guill](https://github.com/guill) , you can also look at this workflow if you are interested in this problem with loops.

Why do I even assume that the problem is with Inpaint Crop - it's just that ComfyUI crashes on Inpaint Crop, as shown in this image:
<img width="1055" alt="error" src="https://github.com/user-attachments/assets/fff8789f-870f-440c-9010-dc7b63cb09a2">

**Comment by lquesada** [comment]
Hi, this sounds like you're running out of memory. Inpaint crop takes 3x-4x
more memory per image because it creates a thick margin up to 0.5x per side
to ensure that any aspect ratio you specify can be fit in the image.

This would mean 4x more memory per image.

I am surprised that this would crash comfyui though.

Are you using a mac? How much shared RAM? This could explain it if you were
very tight in memory already and the images are very large (which the crop
node enables you to process).

Can you monitor your ram while you run this (e.g. with low steps for it to
be faster) and let me know if comfyui is incrementally using more RAM per
loop run? If that is the case, it is very likely an issue in the way
comfyui manages memory, it probably tries to keep every intermediate result
in RAM for the current job in the queue, and that could be improved from
comfyui side to allow running very long jobs (e.g. using for loop).

**Comment by Shyryp** [comment]
Yes, there is a memory overflow.
Each cycle in ForLoop leaves an image in memory.

I am using ComfyUI on Windows 10.

But please make sure that your Inpaint Crop node does not affect new cycles and this memory overflow issue.

I will report the memory overflow to [guill @](https://github.com/guill)

**Comment by lquesada** [comment]
it cannot be the crop node - it doesn't store anything :)

keep me posted with updates to the fix!

**Comment by lquesada** [comment]
From ComfyUI release notes:

Issue News:

[RAM] The issue of rapidly increasing memory usage due to models not being properly released from memory has been fixed.

**Comment by lquesada** [comment]
Another note: I just updated the node with an improvement. Until now, having large images with small masks could trigger huge memory usage because the image was upsized before cropping.

**Comment by Shyryp** [comment]
> Another note: I just updated the node with an improvement. Until now, having large images with small masks could trigger huge memory usage because the image was upsized before cropping.

Ok, thanks!
I'll check it in the next few days.
If something is wrong, I'll let you know.

Thanks for your work!

P.s. Please close this ticket too, or I'll close it myself when I check it:
https://github.com/lquesada/ComfyUI-Inpaint-CropAndStitch/issues/42

**Comment by lquesada** [comment]
done!!
