### ISSUE TITLE
Regular mask produces high quality inpaint but Invert mask produces very low quality inpaint.

### ISSUE THREAD

**Issue by Vigilence** [lquesada/ComfyUI-Inpaint-CropAndStitch#37]
I am using your default workflow with the flux model.  I have Florence2 -> Sam2 create a high quality mask.  If I use the base workflow I can create a very high quality inpaint.  However, if I select the invert mask option, with the same unpainted base image, and the rest of the settings untouched, the inpainted area is very low quality.  The settings are the same as before with the exception of the invert mask option now being selected.

Is there a chance if you have the time, to can verify the invert mask option is working with the latest comfyui update?

**Comment by lquesada** [comment]
Hi, this is because the inpainting area is so much larger if you do the
whole image, so you get it downscaled by the node to fit the target
resolution, and therefore, you lose resolution.

A good solution is to apply a detailer afterwards. I'm figuring out if I
could implement some node that does that detailing for very large images on
a way that's easy to set up with these nodes
